### ISSUE TITLE
Handle broken/missing images

### ISSUE THREAD

**Issue by nickdos** [jackmoore/colorbox#46]
I've found that colorbox (v1.3.15) displays the spinning "loading" icon continuously if I attempt to display an image which returns either an HTTP 404 "NOT FOUND" or a 500 "INTERNAL SERVER ERROR". 

Furthermore, if there are subsequent images in the "group" then hitting the next/previous button also fails. Only the close button appears to function. 

It would be nice if Colorbox exhibited the same behaviour as the browser and displayed the (browser-specific) broken image icon.

**Comment by mc12345678** [comment]
In version 1.6.4, this issue has shown to have resurfaced. In what version was this fixed and/or how would one implement it at version 1.6.4? I thought perhaps there might be a timer that could be used to identify that the image hadn't loaded and to transition to something else.

**Comment by jackmoore** [comment]
@mc12345678 You'll need to be more specific. This ticket as about how Colorbox failed to recover from failed image loading. That has been resolved, as you can move onto prev/next and Colorbox displays a message that the image failed to load:.

<img width="451" alt="Screen Shot 2019-04-16 at 5 01 33 PM" src="https://user-images.githubusercontent.com/59797/56243785-70b12180-6069-11e9-9480-e45799c4c8e2.png">

You can customize this message with the [imgError](http://www.jacklmoore.com/colorbox/#setting-imgError) option.

I assume your issue is something different. You should probably open a new ticket about that, but I don't really do much Colorbox development anymore. I mainly only fix things that might impact legacy users, such as browser changes or jQuery incompatibilities. I hope that makes sense.

**Comment by mc12345678** [comment]
It unfortunately does make sense as this software has shown to be well implemented and flexible. At any rate, you may be appalled by the implementation, I'm not sure, but you can see at this location http://template7.mc12345678.com/v156/index.php?main_page=product_info&products_id=1 that there is a single image in the center, there are no additional images to connect to or to which to "change". The image identified in the image path does not exist on the server (I've changed the name so that it would cause this issue as reported to me at: https://github.com/mc12345678/zen-colorbox/issues/23). On the page in the original link, the imgError is defined but never gets triggered in this arrangement.

As can be seen in the issue thread, there is a suggestion to validate the existence of the file before attempting to propose moving forwards, but there is still something about that which makes me uneasy if a specific path were presented for the purpose of system testing...

I was therefore thinking if the image did not appear after a certain time delay that possibly the viewer auto-closes or swaps to the imgError message or something rather than just spin as reported by the OP. This same spin behavior occurs if there is a super slow connection as well which would be the other reason I was thinking a timer might be beneficial even if it were set to say a minute or 30 seconds even.
