### ISSUE TITLE
Issue with jQuery UI datepicker inside colorbox

### ISSUE THREAD

**Issue by menacestudio** [jackmoore/colorbox#484]
I'm basically injecting raw HTML into colorbox's HTML property and calling the `onComplete` function to add datepicker. It works for inline, but not when using the HTML property. Is this an existing bug or is it an issue with the datepicker itself?

```
onComplete: function() {
     $(".datebox").datepicker({
              changeMonth: true,
              changeYear: true,
              ...
```

**Comment by sl8ar2rk** [comment]
I got the same issue. 
I used an id as selector, but colorbox duplicate the whole html content and the id's too. 
So if I use $('#myid').doSomething() I got an error, because "myid" was duplicated. 
Thats the issus. 

Use a better selector like $('#colorbox .myidasclass').doSomething() to solve the issue. 
The same problem is with class selector without the '#colorbox' as additional selector.
