### ISSUE TITLE
cboxElement class into svg diagram

### ISSUE THREAD

**Issue by TickerPicker** [jackmoore/colorbox#660]
Hello,
i tried to add some modal window (on my <a> tags) into my svg diagram.
Indeed the class cboxElement was not add to my <a> tags, so the modal didn't work.
I had to add this class manually to my tags.
I just wanted to report this "issue". (did I do something wrong ?)

Tell me if I was not clear, I'm not so comfortable with English :)

**Comment by aik099** [comment]
You love clicking Close/Reopen button I see :wink:

**Comment by TickerPicker** [comment]
Sorry, I failed :(

2015-01-06 11:14 GMT+01:00 Alexander Obuhovich <notifications@github.com>:

**Comment by jackmoore** [comment]
Hi TickerPicker, my apologies for the late acknowledgement.  I did not realize until today that jQuery 1.x and 2.x cannot manipulate classes on svg elements, and Colorbox currently uses a class to keep track of which elements it has been assigned to.  This is supposed to be [fixed in jQuery 3.0](http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/) (listed under "Attributes").

I'm sure you don't care about this anymore, but an imperfect fix for this would be to add the 'cboxElement' class to your SVG directly instead of using jQuery.addClass.

**Comment by jerone** [comment]
It looks like class support for SVG is back in jQuery 2.2 and 1.12: http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by jackmoore** [comment]
👍
