### ISSUE TITLE
Removing colorbox for an image link?

### ISSUE THREAD

**Issue by paaljoachim** [jackmoore/colorbox#681]
Hi

I am guessing this is mentioned some where but have not located it yet.
I am using Colorbox for my WordPress web site: http://easywebdesigntutorials.com/
It seems to be working alright there.

I tried sharing a screenshot but noticed that one can not just right click a lightbox poped up image and download it as there is no option to download the image only the full web site.

So I placed a link but since it ends in a jpg I get the pop up cursor and the image pops up like directed.

How can a person easily download an image?
How would I go about removing colorbox from a link?

Thanks.
Happy New Year!

**Comment by jackmoore** [comment]
> How can a person easily download an image?

Normally there is no problem with right-clicking to save an image.  I figured there must have been some CSS issue with your site where an element was laying over the img element, preventing you from getting the correct context menu.  I checked out your site and that does appear to be the case.  The close button is taking up the entire space that the image exists in, and then some.  I'm not sure if this was an intentional change on your part, but if you remove the "padding: 100%" from the #cboxClose element, then you should have no problem right clicking on an image.

> How would I go about removing colorbox from a link?

I need to provide an official / better way of doing this.  But currently you can remove colorbox from any element by removing it's 'cboxElement' class.  For example:
```
$('a.example').removeClass('.cboxElement');
```
I would like to point out that it would be better form to change your colorbox-init.js script so that it only assigns Colorbox to the links you desire, rather than trying to remove it from it links after.

**Comment by paaljoachim** [comment]
Thanks Jack!

I changed the padding to 80% and the context menu also changed so that one can now download the images that I have.

Colorbox is the main lightbox I use for the site. For all the images, so it is a lot easier defining it in the script then defining each image link.

I have a post here in regards to using lightboxes. The article begins with Colorbox. (I am having some difficulty using the gallery code though so I kinda skipped it.)
http://easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/

If you want me to add something to the article do let me know. I am noticing the article is pretty popular  so that I am thinking that we can use it to benefit Colorbox etc as well.
