### ISSUE TITLE
Adding title and alt attribute to popup image

### ISSUE THREAD

**Issue by locker10** [jackmoore/colorbox#700]
Hello,
I created my web site and used your script for popup images.
Now, I have problem. I need add alt and title attribute to popup image.

Please, help me to solve this issue.

**Comment by jackmoore** [comment]
You can now do something like the following:

```
<a class="example" href="example.jpg" data-cbox-img-attrs='{"title": "Hello", "alt"="Goodbye"}'>Grouped Photo 3</a>
```

The `data-cbox-img-attrs` attribute takes in a JSON object of attribute/value pairs you want on the `<img>` element.  However, you can redefine how this works by changing Colorbox's `createImg` property.  The reason I went with the JSON object is because I didn't want to hard-code in which attributes should be checked for.

But if you dislike using the JSON object you could redefine createImg to offer a different means of setting the img attributes.  For example:

```
$.colorbox.settings.createImg = function(){
	var img = new Image();
	var alt = $(this).attr('data-alt');
	var title = $(this).attr('data-title');

	if (alt) {
		img.alt = alt;
	}
	if (title) {
		img.title = title;
	}
	return img;
};
```
