### ISSUE TITLE
jQuery "bind" should be "on"

### ISSUE THREAD

**Issue by jcuenod** [jackmoore/colorbox#720]
Presumably this is familiar to you but for completeness:

> As of jQuery 1.7, the `.on()` method is the preferred method for attaching event handlers to a document. For earlier versions, the `.bind()` method is used for attaching an event handler directly to elements.

http://api.jquery.com/bind/

**Comment by jackmoore** [comment]
I don't want this minor update to break backwards compatibility with previous versions of jQuery.  There a lot of people stuck on legacy jQuery due to being on older frameworks that consume updated versions of this plugin through their framework plugin managers.  I'd prefer to use `on`, but in versions of jQuery that have `on` it's the same thing as `bind` (`bind` doesn't have it's own logic any more, it just passes it's arguments to `on`).

**Comment by jcuenod** [comment]
Fair enough. Could come in a major version update though. I guess it's 
just worth noting.
Thanks for the response.

**Comment by jackmoore** [comment]
Thank you.
