### ISSUE TITLE
Stack overflow

### ISSUE THREAD

**Issue by crazylive** [jackmoore/colorbox#724]
Sorry, for what reason variable $loadbay used? just this element gets the whole page. Page loaded together with metatags & js-scripts, DOM turns into hell, if called $.сolorbox with Ajax several times i have returned the error stack overflow. Tell me maybe I'm wrong

**Comment by jackmoore** [comment]
The loadingbay element would be irrelevant to this behavior, it's just a place in the DOM to put your ajax content so that the width and height can be measured.  The problem is that you loaded an entire HTML document through ajax.  Regardless of what Colorbox does, jQuery is going to automatically add any script elements from that to the main document, causing a mess.  Adding stylesheets and creating invalid nesting of HTML elements is a problem too.

Colorbox does use [jQuery's load method](http://api.jquery.com/load/) so you can include a selector to insert just a fragment of the document.  I'm not sure if jQuery will still insert scripts from parts of the document outside of the fragment.

Example of getting just a fragment of the document with Colorbox:
```
$('a.example').colorbox({href: 'ajax.html body'});
```

**Comment by crazylive** [comment]
thank you very much :) I was inattentive when read documentation
