### ISSUE TITLE
iFrame Contents removed When Closing Colobox Modal

### ISSUE THREAD

**Issue by WScott84** [jackmoore/colorbox#748]
Hi,

Please see this site, http://www.injoyvideos.com, click login at the top right, and login with scott@unleadedGroup.com / unleaded123 as the username / password.

Go to http://injoyvideos.com/customerclass/class/list/ and click "Understanding Birth Classroom Website".  A popup will open.  Wait for the page to fully load, and then click "Full Chapter" under "Understand Pregnancy".  A lightbox with a video will popup.  Close the light box, reopen the lightbox and the video is missing.  The contents of the iframe has disappeared.

**Comment by jackmoore** [comment]
Sorry, your link doesn't appear to be working.

**Comment by WScott84** [comment]
Here is the link again: http://injoyvideos.com/

**Comment by WScott84** [comment]
Did you login before clicking the 2nd link?

**Comment by jackmoore** [comment]
You are right, sorry, I needed to log in.  I see the problem you are describing.  The short answer is this is not an issue with Colorbox (or at least I'm not aware of any way to avoid it), as the content you are trying to display in Colorbox does is not conducive to being moved around the DOM once it has rendered.  Instead of using Colorbox's inline option, I would suggest using the iframe option or html option.  These would allow for a new iframe to be created each time, instead of trying to reusing an existing on.

Going to close this as it's a browser limitation, rather than something Colorbox can control.
