### ISSUE TITLE
Conflict with Floating Social Bar Plugin in WordPress

### ISSUE THREAD

**Issue by frank6tg** [jackmoore/colorbox#750]
When sites using "Simple Colorbox" plugin also use "Floating Social Bar" (FSB) Plugin the colorbox "picks up" an extra image which forces an error message.

You can view this behavior on any blog post of mine: Example: http://franksdesigns.com/custom-return-address-stamps/

YOu'll see 3 images, the Colorbox reports 4 images, loads the second image first (the first REAL image) If you go back to the first image you get a blank item with this error: "This image failed to load."

**Comment by jackmoore** [comment]
Colorbox is doing exactly what it was told to do.  You need to change how you assign Colorbox so that it only selects the elements you want it to. 
And you have 4 links on that page that end in '.jpg'.  This is the first one:

```
<a href="http://pinterest.com/pin/create/button/?url=http://franksdesigns.com/custom-return-address-stamps/&description=Custom+Return+Address+Stamps&media=http://franksdesigns.com/wp-content/uploads/SKK-Return-Address-Stamp.jpg" class="socialite pinit fsb-pinterest" data-fsb-service="pinterest" target="_blank" rel="nofollow"><span class="fsb-service-title">Pinterest</span><span class="fsb-count">0</span></a>
```

This is how your page currently assigns Colorbox:

```
jQuery(function($){ 
			// Examples of how to assign the ColorBox event to elements 
			$("a[href$=\'jpg\'],a[href$=\'jpeg\'],a[href$=\'png\'],a[href$=\'bmp\'],a[href$=\'gif\'],a[href$=\'JPG\'],a[href$=\'JPEG\'],a[href$=\'PNG\'],a[href$=\'BMP\'],a[href$=\'GIF\']").colorbox(colorboxSettings); 
		});;
```

You will want make this more restrictive and specific to your site, so that it only selects the images you are interested in showing in the lightbox.  For this page, you could do something like this instead:

```
jQuery(function($){
    $('.gallery-icon a').colorbox(colorboxSettings);
});
```
