### ISSUE TITLE
setClass sets classes once

### ISSUE THREAD

**Issue by oscar-g** [jackmoore/colorbox#752]
What is the reasoning for storing the class string in the `setClass` function (line 267)?

````
if (setClass.str !== str) {
	$box.add($overlay).removeClass(setClass.str).addClass(str);
	setClass.str = str;
}
````

In my particular use case, I the `className` option to set classes that eventually trigger css transitions.  For example, I set the option `className = 'from-the-left'` and the callback `onComplete` does something like: `$('.from-the-left').addClass('open')`.  In the css, `.from-the-left` hides the element on the left and `.open` brings it in from the left (all of this using css `translate3d`).  Finally, at the callback `onClosed`, I remove both of these classes.

This works great the first time I trigger colorbox, but, because of the logic in `setClass`, the colorbox script doesn't set the classes again when its triggered the second time.

My solution right now is to just uncomment this logic, but I am curious as to why we have the logic in the first place.

Thanks,
Oscar G

**Comment by jackmoore** [comment]
If you were to open Colorbox again, while it was already open, then the quoted logic would check to see if the new option has a different className, and if so, remove the old one.  Colorbox has persistence in the DOM, rather than being replaced each time it is opened with new content, so the old class needs to be removed if the option has changed.  I failed to anticipate this class being removed by another means.  You should be able to do something like this:

```
if (setClass.str !== str) {
    $box.add($overlay).removeClass(setClass.str);
    setClass.str = str;
}
$box.add($overlay).addClass(str);
```

Or you could probably use the onOpen callback to set your class instead.

**Comment by oscar-g** [comment]
Thanks for the response, @jackmoore 

I'll use `onOpen` instead of modifying the source.
