### ISSUE TITLE
Colorbox throwing errors in IE browsers

### ISSUE THREAD

**Issue by video-internal** [jackmoore/colorbox#760]
Hi Jack,

We're opening youtube video that is pulled using YouTube's iFrame API in the colrobox within our own custom build video player. It is working as per expectation in chrome and firefox. But if I open that same video player  in IE browsers [ version-11,10 and 9], it is throwing errors in www-embed-player-new.js I know this js is coming from youtube's end but do you know anything related to this which is causing issues when we open youtube's video in colorbox?

We're using ColorBox v1.3.9 and jquery-1.8.2.min.js for this video player.

For your reference,

URL of the page: http://visualisation.investis.com/video/requirejs+angularjs/www_yt1/investisSinglePlayer_multipleIntegration.html

Can you or anyone else who may have encountered this problem earlier please help us in solving this problem?

**Comment by jackmoore** [comment]
Sorry, at a cursory glance I couldn't determine what the problem is.  But, I do not feel like it's specific to Colorbox.  My suggestion would be to use something other than inline content, as some applications won't respond well to being moved around the DOM (iframes also have a problem with being moved around in the DOM, but I don't think that's an issue here).  I would suggest reworking it so that you use something like Colorbox's html property, and let *all* of the video player setup and teardown happen within Colorbox's onComplete and onCleanup callbacks (it looks you do some player initialization while the embed code is still in the main document currently).
