### ISSUE TITLE
colorbox.css - z-index issue

### ISSUE THREAD

**Issue by knubew** [jackmoore/colorbox#763]
Not really an issue, but...

I had problems with a customer website, which uses very high z-index partially. So the Colorbox overlay was not displayed correctly. I've raised the the z-index to 999999 in line 5 of colorbox.css and added an !important declaration.

+++ Original +++
#colorbox, #cboxOverlay, #cboxWrapper{position:absolute; top:0; left:0; z-index:9999; overflow:hidden; -webkit-transform: translate3d(0,0,0);}

+++ New +++
#colorbox, #cboxOverlay, #cboxWrapper{position:absolute; top:0; left:0; z-index:999999 !important; overflow:hidden; -webkit-transform:translate3d(0,0,0);}

Maybe it's also a useful change for Colorbox in general !?

**Comment by jackmoore** [comment]
Thanks for the input.  The current z-index value was arbitrarily chosen, for sure.  It's not really possible for Colorbox to pick a z-index that is going to work for everyone (sometimes you want stuff to show up on top of Colorbox's overlay, such as a feedback or contact button).  

Since there isn't a right z-index, sticking with the current value is probably best for legacy reasons.  Adding the !important modifier by default would be more aggressive than I'm confortable with.
