### ISSUE TITLE
incorrect rendering of iframe

### ISSUE THREAD

**Issue by flyfj** [jackmoore/colorbox#779]
everything works pretty well, except when i tested on instagram, the box is rendered completely wrong. I attached an image (using style in example1). really struggling, any idea how to fix this?
THANKS A LOT
![colorbox_err](https://cloud.githubusercontent.com/assets/2397970/14661433/9394ffe6-067b-11e6-9bc6-f9e468c21364.png)

**Comment by flyfj** [comment]
i think i just found the same issue [here](https://github.com/jackmoore/colorbox/issues/162).

**Comment by flyfj** [comment]
anyone can help with this? thank you so much

**Comment by jackmoore** [comment]
I don't have any suggestions beyond what was already said in the other thread.  If the CSS is loaded after Colorbox is called, that would be the issue, but this rarely comes up because CSS loading happens in the head of the document and is synchronous.  I imagine the issue is due to some global style that is being inadvertently applied to Colorbox's DOM elements.  If you post a link to a demo I would have a look at it.
