### ISSUE TITLE
possibly a bug - video not working on chrome, but works on safari

### ISSUE THREAD

**Issue by flyfj** [jackmoore/colorbox#780]
I'm using the latest version. 
strange issue, video not playing on chrome, only show a static image of the video, can't click on anything. but it plays on safari.

Take a look at the image below, when error happens, the display seems to be wrong also. (on chrome)
the demo of example 3 on colorbox website also not work for me.
![screen shot 2016-05-02 at 4 06 28 am](https://cloud.githubusercontent.com/assets/2397970/14949883/82b99f2a-101b-11e6-81e3-754a1d57ea5c.png)
when it work, the box displays correctly without the white boundary. (on safari)
![screen shot 2016-05-02 at 4 07 12 am](https://cloud.githubusercontent.com/assets/2397970/14949885/85d62b88-101b-11e6-9d43-d712f1be85a2.png)

**Comment by flyfj** [comment]
problem found. it is because of css in example 3. when i tried example 1, it works on both browser. please take a look at this.

**Comment by jackmoore** [comment]
I could not reproduce the issue, worked fine in Safari for me and it doesn't really follow that a CSS change would impact how a video is playing in an iframe.  Any video playback issues would probably be unrelated to Colorbox anyway, since it doesn't have any control over how a browser renders content within an iframe.
