### ISSUE TITLE
Delay between onCleanup and the closing of the colorbox?

### ISSUE THREAD

**Issue by KingWebsites** [jackmoore/colorbox#782]
Hi, is there a way to delay the closing of the colorbox after the close event has happened?

I'm having lots of issues with ckeditor instances possibly breaking my Single Page Application and (on iOS) forcing the keyboard to keep popping up after a colorbox containing a ckeditor is closed.

I'm calling the colorbox like so:

`
$.colorbox({

	transition: 'fade',

	html: modalHTML,

	maxWidth: '636px',

	height: '700px',  

	returnFocus: false,  

	trapFocus: true,  

	closeButton: false,  

	preloading: false,  

	fixed: true,  

	onCleanup: function() {  

		destroyCkeditorInstances();  

	}  

});
`

Where destroyCkeditorInstances() is a function I wrote that gets rid of all my ckeditor boxes.

To solve my annoying keyboard issue (which only happens with colorbox) I think I need to:
1. User clicks the colorbox 'close' button.
2. Before anything else happens I run destroyCkeditorInstances() to make sure that the ckeditor sessions are closed properly and the dom's 'focus' element isn't in limbo.
3. After that's has happened (maybe just using a timeout 500) I want the usual closure of the colorbox.

Is trying to do this in onCleanup already too late? What do you suggest I can use to leave a gap of 500 second between the click and the actual hiding of the modal window? Thanks.

**Comment by jackmoore** [comment]
That looks to me like you are doing things correctly, so I'm not sure what to say.  The onCleanup callback shouldn't be too late as long as destroyCkeditorInstances is synchronous (I assume it would be, it would be odd if it wasn't).  The CKEditor destroy method should finish before Colorbox removes it's content elements from the DOM.  Adding a delay seems like a superstitious way to resolve it, but I can't say for sure that it won't work because I have no knowledge of how destroyCkeditorInstances functions.

Colorbox has no built in way of delaying closing in which it dumps it's content.  Either you would have to modify Colorbox to support that behavior, or remove Colorbox's default events that trigger closing and handle that yourself, or replace Colorbox's close method with your own. There is an [FAQ entry](http://www.jacklmoore.com/colorbox/faq/#faq-close) for that last suggestion that might help.

I think this would work, but it's been a long time since I've done something like this:

```
var originalClose = $.colorbox.close;
var timeout;

$.colorbox.close = function(){
    destroyCkeditorInstances();

    if (timeout) {
	    clearTimeout(timeout);
    }

    timeout = setTimeout(originalClose, 500);
};

$('a#example').colorbox();
```

**Comment by KingWebsites** [comment]
Thanks for your response. I will update and close this issue soon with the solution I use.

**Comment by KingWebsites** [comment]
Hi Jack, I've read back what you've said and it kind of confirmed what I thought, that colorbox is doing everything correctly and it is the ckeditor and the way that it handles 'focus' that is at fault, causing the annoying keyboard popping up issue.

I have created a workaround solution for this so I thought I'd detail it here in case others come up against similar issues. What I did was, in addition to the 'onCleanup' function, use your 'onClosed' callback to create / focus / blur / remove a temporary input field. This removes any vagueness about what DOM element has focus and seems to work fine:

```
onClosed: function() {
 // Fix for iOS issue of keyboard popping up.
 $('.wrapper').append('<input style="position: fixed; top: 50%; left: 50%;" type="text" id="temp-ios-fix" value=""/>');
 $('.wrapper input#temp-ios-fix').focus();
 $('.wrapper input#temp-ios-fix').blur();
 $('.wrapper input#temp-ios-fix').remove();
}
```

I appreciate your help. Thanks.
