### ISSUE TITLE
Guard Against Ad-Blockers?  Blocked by Crystal (iOS Ad-Blocker)

### ISSUE THREAD

**Issue by mike-zarandona** [jackmoore/colorbox#806]
Is there any way to "guard" colorbox against ad-blockers such as [Crystal](http://crystalapp.co/)?  I was banging my head for two days until I realized disabling Crystal caused colorbox to work as intended.  However I realize this may just be the nature of the beast, and there might not be much we can do about it.

Cheers.

**Comment by jackmoore** [comment]
I hadn't considered this before, but now I'm surprised this is the first time this has come up.  So ad blockers block by referrer, but also by specific and wildcard element selectors.  If you give something an id of 'something_ad', there is a good chance blockers are going to remove the element.  

My guess is that some site used Colorbox to show an ad, and some visitor right-clicked on Colorbox and added it's selector to the blacklist, rather than filtering down more specifically to the ad (the ad may not have even had an easily targetable selector, for obvious reasons).  My suggestion would be to edit your colorbox.js or colorbox.min.js and change the `prefix` variable from `'cbox'` to some new value.  That will change all of Colorbox's ids to be prefixed with your new value, which should avoid the blacklist if that was the blocking mechanism.  Remember to also replace `cbox` in colorbox.css with your new prefix value.

**Comment by mike-zarandona** [comment]
I'm equally shocked at the fact that it took me so long to see this issue, having used colorbox on many sites before this implementation.

In order to get things working in an iOS ad-blocking environment, I had to change both the `prefix` and the `colorbox` namespacing (it looks like the ID `#colorbox` got tagged as "spammy" by some blacklist somewhere).

So (for posterity) I wound up having to change:

- jquery.colorbox.js:125  
    `colorbox = 'otherbox',`
- jquery.colorbox.js:126  
    `prefix = 'othr'`
- colorbox.css  
    - Find + replace namespacing "`#colorbox`" with "`#otherbox`"
    - Find + replace prefix "`cbox`" with "`othr`"
- Change actual call to colorbox  
    `$('a.gallery-item').otherbox({ ... });`

Thanks for the quick update on this.  The foresight to include options for abstracting the HTML and event identifiers made this a really easy fix. 👍
