### ISSUE TITLE
Cut off of bottom of modal problem

### ISSUE THREAD

**Issue by ash-f** [jackmoore/colorbox#825]
It's not an image but html elements from ajax api, also responsive design so I can not set the height.
Somehow problem does not happen to any modal on the page if it's not first time.
Once opened (any) model smoothly show up without cut off.

**Comment by jackmoore** [comment]
The FAQ entry I linked you to was specific to HTML content, just like you are using.  Your HTML content has <img> elements in it that need width and height attributes so that the modal can be sized accurately before the images finish loading.

**Comment by ash-f** [comment]
If I set width/height to modal content through js dynamically in onComplete:function() before resize(), does it work, by any chance?

I have many modal with different sizes, also its size will change depend on screen size.
so specify size to each modal content is bit tough.

**Comment by jackmoore** [comment]
I would avoid calling resize if you can prevent it, and you can prevent it if you just add the width and height attributes to your `<img>` elements. Sorry, Colorbox is an old script that doesn't handle progressive loading or responsiveness that well.

**Comment by ash-f** [comment]
Thank you. I'll try to set height/width to imgs somehow.
Does min-height/min-width & max-height/max-width of imgs affects to modal size?

**Comment by jackmoore** [comment]
Yes, any CSS style that impacts layout.  Like the width and height attributes, CSS styles are immediately available, allowing those impacts to layout to be calculated once your markup has been added to the DOM.  Since your `<img>` elements currently lack a width/height attr, or CSS width/height/min-width/min-height, they will initially have 0x0 size until the image has loaded.  Hope that makes sense.

**Comment by ash-f** [comment]
Thank you very much.
