### ISSUE TITLE
XSS vulnerability when supplying user input in the title attribute.

### ISSUE THREAD

**Issue by Addono** [jackmoore/colorbox#846]
When HTML escaped user input is added to the title attribute of a Colorbox element it, will it still be executed when the Colorbox is opened.

For example when the user entered `<script>alert('XSSed')</script>` and this is atted to the title attribute of a Colorbox, like `&lt;script&gt;alert('XSSed')&lt;/script&gt;`, will the code still be executed when the Colorbox be opened.
````
...
<a class="xss" href="img.jpg" title="User supplied string: &lt;script&gt;alert('XSSed')&lt;/script&gt;">Single encoded</a>
...
````
![Example of the XSS vulnerability](https://i.imgur.com/Ai92r3s.png)

For the full example see [this example](https://github.com/Addono/colorbox/tree/xss-example).

**Comment by jackmoore** [comment]
Thanks for the detailed description and pull request. This is as is intended, as some people like to add formatting or links to the title, and merging your pull request would break things for some existing users.  User-generated strings was not something I originally accounted for, but it's a reasonable request.

I don't know if this is an adequate solution for you, but you can overwrite the function that resolves the value that is passed to `$title.html()`, which would allow you to encode the text so that it's safe for insertion.  Here's an example I think would work:

```js
$.colorbox.settings.title = function() {
  var escape = document.createElement('textarea');
  escape.textContent = this.title;
  return escape.innerHTML;
}
```

**Comment by jackmoore** [comment]
Alternatively, you could also do this:

```js
$(".example").colorbox({
  title: false, 
  onComplete: function(){
    $('#cboxTitle').text(this.title)
  }
});
```

**Comment by Addono** [comment]
I understand that BC is important, the solution you proposed on overwriting the title function seems the best workaround. It results in some code duplication, but it works so it is fine.

Keep up the good work.

**Comment by Addono** [comment]
And for others using this solution, if you are not certain if the title attribute is set then you have to add a check, else it might result in setting the title to "undefined" when none is actually parsed.
